spring.application.name=customer-service

server.port=8083

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/shopsphere
spring.datasource.username=shopsphere
spring.datasource.password=shopsphere_dev_password

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Database schema
spring.jpa.properties.hibernate.default_schema=customer

# Flyway
spring.flyway.enabled=true
spring.flyway.default-schema=customer
spring.flyway.schemas=customer
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,info