spring.application.name=inventory-service

server.port=8084

spring.datasource.url=jdbc:postgresql://postgres:5432/shopsphere?options=-c%20TimeZone=Asia/Kolkata
spring.datasource.username=shopsphere
spring.datasource.password=shopsphere_dev_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=inventory

spring.flyway.enabled=true
spring.flyway.default-schema=inventory
spring.flyway.schemas=inventory
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info